### ISSUE TITLE
Animus cant launch due to item missing

### ISSUE THREAD

**Issue by kristareingarcia600-art** [TeamDman/Animus#94]
I think a similar problem to a problem 2 weeks ago but this time it wont do it even after downloading the optional dependency.
Without Malum:
[crash-2025-12-19_22.11.34-fml.txt](https://github.com/user-attachments/files/24259666/crash-2025-12-19_22.11.34-fml.txt)
With Malum
[crash-2025-12-19_22.27.24-fml.txt](https://github.com/user-attachments/files/24259697/crash-2025-12-19_22.27.24-fml.txt)

**Comment by Saereth** [comment]
This should already be fixed. I see in your logs you're on version 3.0.5 of Animus, try updating to 3.0.9 and let me know if you experience the issue again (should not). Thanks!

**Comment by kristareingarcia600-art** [comment]
Just updated, still not working
[crash-2025-12-20_00.47.37-fml.txt](https://github.com/user-attachments/files/24261890/crash-2025-12-20_00.47.37-fml.txt)

**Comment by Saereth** [comment]
oh I see the issue, you have Blood Magic 3.3.3-45 but we compile against Blood Magic 3.3.5-47. The class ItemSentientScythe path changed between these versions. I will update the mod's dependencies next version to prevent this from running with the older BM version.
